sudo: false
cache: bundler
language: ruby
rvm:
  - 2.3.0
env:
  matrix:
    - SOLIDUS_BRANCH=v1.0
    - SOLIDUS_BRANCH=v1.1
    - SOLIDUS_BRANCH=v1.2
    - SOLIDUS_BRANCH=v1.3
    - SOLIDUS_BRANCH=master
