language: ruby
rvm:
  - 2.1
  - 2.2
sudo: false
cache: bundler
env:
  matrix:
    - SOLIDUS_BRANCH=master
    - SOLIDUS_BRANCH=v1.2
    - SOLIDUS_BRANCH=v1.1
before_script:
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
